---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logcollector-audit-logs-binding
  namespace: openshift-logging
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-audit-logs
subjects:
- kind: ServiceAccount
  name: logcollector
  namespace: openshift-logging
