apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  {{- if .spec.outputs }}
  outputs:
    - type: {{ (index .spec.outputs 0).type }}
      name: {{ (index .spec.outputs 0).name }}
      kafka:
        url: {{ (index .spec.outputs 0).kafka.url }}
  {{- end }}
  {{- if .spec.filters }}
  filters:
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  {{- if .spec.pipelines }}
  pipelines:
    {{- range .spec.pipelines }}
    - inputRefs:
        {{- range .inputRefs }}
          {{- if ne . "application" }}
      - {{ . }}
          {{- end }}
        {{- end }}
      name: {{ .name }}
      outputRefs:
        {{- range .outputRefs }}
      - {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
  serviceAccount:
    name: logcollector
