apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
    name: {{ .metadata.name }}
    annotations:
        ran.openshift.io/ztp-deploy-wave: "1"
spec:
{{ if .spec.repositoryDigestMirrors }}
  repositoryDigestMirrors:
{{ .spec.repositoryDigestMirrors | toYaml | indent 2 }}
{{end}}
