---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group-zones-configmap
  namespace: ztp-group
data:
  # ClusterLogForwarder.yaml
  zone-1-cluster-log-fwd-outputs: "[{\"name\":\"default-lokistack\",\"type\":\"lokiStack\",\"lokiStack\":{\"target\":{\"name\":\"logging-loki\",\"namespace\":\"openshift-logging\"},\"authorization\":{\"token\":{\"from\":\"serviceAccount\"}}},\"tls\":{\"ca\":{\"key\":\"service-ca.crt\",\"configMapName\":\"openshift-service-ca.crt\"}}}]"
  zone-1-cluster-log-fwd-pipelines: "[{\"name\":\"all-to-default\",\"inputRefs\":[\"applications\",\"audit\",\"infrastructure\"],\"outputRefs\":[\"default-lokistack\"]}]"
  # StoragePVC.yaml
  zone-1-storagepvc-storage: "100Gi"
