apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: {{ .metadata.name }}
  namespace: "openshift-local-storage"
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  logLevel: Normal
  managementState: Managed
