---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-du-sno"
  namespace: "group-du-sno-policies"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  sourceFiles:
    # Set ClusterLogForwarder and Lokistack as example might be better to create another policyTemp-Group
    - fileName: ClusterLogForwarder.yaml
      policyName: "log-forwarder-policy"
      spec:
        serviceAccount:
          name: logcollector
        outputs:
          - name: default-lokistack
            type: lokiStack
            lokiStack:
              target:
                name: logging-loki
                namespace: openshift-logging
              authorization:
                token:
                  from: serviceAccount
            tls:
              ca:
                key: service-ca.crt
                configMapName: openshift-service-ca.crt
        pipelines:
        - name: all-to-default
          inputRefs:
            - applications
            - audit
            - infrastructure
          outputRefs:
          - default-lokistack
    - fileName: LokiStack.yaml
      policyName: "lokistack-policy"
      spec:
        storageClassName: fs-loki-logging
    - fileName: StoragePVC.yaml
      policyName: "lokistack-storage-policy"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: "fs-loki-logging"
    - fileName: MachineConfigSctp.yaml
      policyName: "mc-sctp-policy"
      metadata:
        labels:
          machineconfiguration.openshift.io/role: master
    - fileName: PtpConfigSlave.yaml
      policyName: "ptp-config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          interface: "ens5f0"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
    - fileName: SriovOperatorConfig.yaml
      policyName: "sriov-operconfig-policy"
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "disable-network-diag"
      metadata:
        labels:
          machineconfiguration.openshift.io/role: master
    # # AmqInstance is required if PTP and BMER operators use AMQP transport
    # - fileName: AmqInstance.yaml
