apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  name: default
  namespace: openshift-sriov-network-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  {{- if .spec.configDaemonNodeSelector }}
  configDaemonNodeSelector:
    {{ template "matchNodeSelector" (list .spec.configDaemonNodeSelector "node-role.kubernetes.io" ) }}
  {{- end }}
  enableInjector: false
  enableOperatorWebhook: false
  # Disable drain is needed for Single Node Openshift
  disableDrain: true
  logLevel: 0
