apiVersion: v1
kind: Namespace
metadata:
  name: vran-acceleration-operators
  {{- if .metadata.labels }}
  labels:
    {{- template "allowLabels" (list .metadata.labels
        "pod-security.kubernetes.io"
    ) }}
  {{- end }}
