apiVersion: "observability.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
#  outputs: $outputs
#  pipelines: $pipelines

#apiVersion: "observability.openshift.io/v1"
#kind: ClusterLogForwarder
#metadata:
#  name: instance
#  namespace: openshift-logging
#spec:
#  serviceAccount:
#   name: logcollector
#  outputs:
#    - name: default-lokistack
#      type: lokiStack
#      lokiStack:
#        target:
#          name: logging-loki
#          namespace: openshift-logging
#        authorization:
#          token:
#            from: serviceAccount
#      tls:
#       ca:
#         key: service-ca.crt
#         configMapName: openshift-service-ca.crt
#  pipelines:
#  - name: all-to-default
#    inputRefs:
#      - applications
#      - audit
#      - infrastructure
#    outputRefs:
#    - default-lokistack
